# Generated by Django 5.2.1 on 2025-08-10 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_user_id_remove_project_sheduled_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='achievement_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了実績日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='achievement_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始実績日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='プロジェクト名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了予定日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始予定日'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('未着手', '未着手'), ('進行中', '進行中'), ('完了', '完了')], max_length=50, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='task',
            name='achievement_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了実績日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='achievement_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始実績日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了予定日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始予定日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('未着手', '未着手'), ('進行中', '進行中'), ('完了', '完了')], max_length=50, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=100, verbose_name='タスク名'),
        ),
    ]
